Added refreshing the page after changing the domain.
skilld-labs/domain pull request #3
Opened 2017-04-24 14:42 UTC by BasilSnowman

Added refreshing the page after changing the domain (for real info on the configuration).

2017-04-24 14:49 UTC, andypost requested changes
Current request is the main question

2017-04-24 14:49 UTC, andypost commented on domain_config_ui/src/Form/SwitchForm.php
> +    $url = Url::createFromRequest($this->requestStack->getCurrentRequest());
Are you sure that current request is the same as current page has?

2017-04-24 14:50 UTC, andypost commented on domain_config_ui/src/Form/SwitchForm.php
> +   * @return AjaxResponse
Needs new line before for code style

2017-04-25 09:09 UTC, BasilSnowman commented on domain_config_ui/src/Form/SwitchForm.php
> +   * @return AjaxResponse
fixed

2017-04-25 09:14 UTC, andypost commented on domain_config_ui/src/Form/SwitchForm.php
> +      $url = Url::fromUri('base:' . $path);
Needs to call setAbsolute() before redirect, isn't it?

2017-04-25 09:36 UTC, BasilSnowman commented on domain_config_ui/src/Form/SwitchForm.php
> +      $url = Url::fromUri('base:' . $path);
yes, you right

2017-04-25 09:42 UTC, merged